/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlaylistUpdate model module.
 * @module model/PlaylistUpdate
 * @version 0.1.0
 */
class PlaylistUpdate {
    /**
     * Constructs a new <code>PlaylistUpdate</code>.
     * @alias module:model/PlaylistUpdate
     * @param name {String} 
     */
    constructor(name) { 
        
        PlaylistUpdate.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>PlaylistUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlaylistUpdate} obj Optional instance to populate.
     * @return {module:model/PlaylistUpdate} The populated <code>PlaylistUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaylistUpdate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], 'String');
            }
            if (data.hasOwnProperty('ordered_tracks_spotify_ids')) {
                obj['ordered_tracks_spotify_ids'] = ApiClient.convertToType(data['ordered_tracks_spotify_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlaylistUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlaylistUpdate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PlaylistUpdate.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['genre'] && !(typeof data['genre'] === 'string' || data['genre'] instanceof String)) {
            throw new Error("Expected the field `genre` to be a primitive type in the JSON string but got " + data['genre']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ordered_tracks_spotify_ids'])) {
            throw new Error("Expected the field `ordered_tracks_spotify_ids` to be an array in the JSON data but got " + data['ordered_tracks_spotify_ids']);
        }

        return true;
    }


}

PlaylistUpdate.RequiredProperties = ["name"];

/**
 * @member {String} name
 */
PlaylistUpdate.prototype['name'] = undefined;

/**
 * @member {String} genre
 * @default ''
 */
PlaylistUpdate.prototype['genre'] = '';

/**
 * @member {Array.<String>} ordered_tracks_spotify_ids
 */
PlaylistUpdate.prototype['ordered_tracks_spotify_ids'] = undefined;






export default PlaylistUpdate;

