/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';
import PlaylistCreate from '../model/PlaylistCreate';
import PlaylistUpdate from '../model/PlaylistUpdate';

/**
* Playlist service.
* @module api/PlaylistApi
* @version 0.1.0
*/
export default class PlaylistApi {

    /**
    * Constructs a new PlaylistApi. 
    * @alias module:api/PlaylistApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deletePlaylistApiV1AdminPlaylistPlaylistIdDelete operation.
     * @callback module:api/PlaylistApi~deletePlaylistApiV1AdminPlaylistPlaylistIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Playlist
     * @param {Number} playlistId 
     * @param {module:api/PlaylistApi~deletePlaylistApiV1AdminPlaylistPlaylistIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deletePlaylistApiV1AdminPlaylistPlaylistIdDelete(playlistId, callback) {
      let postBody = null;
      // verify the required parameter 'playlistId' is set
      if (playlistId === undefined || playlistId === null) {
        throw new Error("Missing the required parameter 'playlistId' when calling deletePlaylistApiV1AdminPlaylistPlaylistIdDelete");
      }

      let pathParams = {
        'playlist_id': playlistId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/admin/playlist/{playlist_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPlaylistApiV1AdminPlaylistPlaylistIdGet operation.
     * @callback module:api/PlaylistApi~getPlaylistApiV1AdminPlaylistPlaylistIdGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Playlist
     * @param {Number} playlistId 
     * @param {module:api/PlaylistApi~getPlaylistApiV1AdminPlaylistPlaylistIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getPlaylistApiV1AdminPlaylistPlaylistIdGet(playlistId, callback) {
      let postBody = null;
      // verify the required parameter 'playlistId' is set
      if (playlistId === undefined || playlistId === null) {
        throw new Error("Missing the required parameter 'playlistId' when calling getPlaylistApiV1AdminPlaylistPlaylistIdGet");
      }

      let pathParams = {
        'playlist_id': playlistId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/admin/playlist/{playlist_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPlaylistsApiV1AdminPlaylistGet operation.
     * @callback module:api/PlaylistApi~getPlaylistsApiV1AdminPlaylistGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Playlists
     * @param {Object} opts Optional parameters
     * @param {Number} [start = 0)] 
     * @param {Number} [limit = 20)] 
     * @param {module:api/PlaylistApi~getPlaylistsApiV1AdminPlaylistGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getPlaylistsApiV1AdminPlaylistGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'start': opts['start'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/admin/playlist/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the newPlaylistApiV1AdminPlaylistPost operation.
     * @callback module:api/PlaylistApi~newPlaylistApiV1AdminPlaylistPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * New Playlist
     * @param {module:model/PlaylistCreate} playlistCreate 
     * @param {module:api/PlaylistApi~newPlaylistApiV1AdminPlaylistPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    newPlaylistApiV1AdminPlaylistPost(playlistCreate, callback) {
      let postBody = playlistCreate;
      // verify the required parameter 'playlistCreate' is set
      if (playlistCreate === undefined || playlistCreate === null) {
        throw new Error("Missing the required parameter 'playlistCreate' when calling newPlaylistApiV1AdminPlaylistPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/admin/playlist/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut operation.
     * @callback module:api/PlaylistApi~updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Cover Image
     * @param {Number} playlistId 
     * @param {File} coverFile 
     * @param {module:api/PlaylistApi~updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut(playlistId, coverFile, callback) {
      let postBody = null;
      // verify the required parameter 'playlistId' is set
      if (playlistId === undefined || playlistId === null) {
        throw new Error("Missing the required parameter 'playlistId' when calling updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut");
      }
      // verify the required parameter 'coverFile' is set
      if (coverFile === undefined || coverFile === null) {
        throw new Error("Missing the required parameter 'coverFile' when calling updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut");
      }

      let pathParams = {
        'playlist_id': playlistId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'cover_file': coverFile
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/admin/playlist/{playlist_id}/cover-image', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePlaylistApiV1AdminPlaylistPlaylistIdPut operation.
     * @callback module:api/PlaylistApi~updatePlaylistApiV1AdminPlaylistPlaylistIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Playlist
     * @param {Number} playlistId 
     * @param {module:model/PlaylistUpdate} playlistUpdate 
     * @param {module:api/PlaylistApi~updatePlaylistApiV1AdminPlaylistPlaylistIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updatePlaylistApiV1AdminPlaylistPlaylistIdPut(playlistId, playlistUpdate, callback) {
      let postBody = playlistUpdate;
      // verify the required parameter 'playlistId' is set
      if (playlistId === undefined || playlistId === null) {
        throw new Error("Missing the required parameter 'playlistId' when calling updatePlaylistApiV1AdminPlaylistPlaylistIdPut");
      }
      // verify the required parameter 'playlistUpdate' is set
      if (playlistUpdate === undefined || playlistUpdate === null) {
        throw new Error("Missing the required parameter 'playlistUpdate' when calling updatePlaylistApiV1AdminPlaylistPlaylistIdPut");
      }

      let pathParams = {
        'playlist_id': playlistId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/admin/playlist/{playlist_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
