/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import HTTPValidationError from './model/HTTPValidationError';
import PlaylistCreate from './model/PlaylistCreate';
import PlaylistUpdate from './model/PlaylistUpdate';
import RatingSchema from './model/RatingSchema';
import URLCreateUpdate from './model/URLCreateUpdate';
import ValidationError from './model/ValidationError';
import ValidationErrorLocInner from './model/ValidationErrorLocInner';
import AdminApi from './api/AdminApi';
import DefaultApi from './api/DefaultApi';
import PlaylistApi from './api/PlaylistApi';
import SpotifyApi from './api/SpotifyApi';
import UrlApi from './api/UrlApi';
import UserApi from './api/UserApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FastApi = require('index'); // See note below*.
* var xxxSvc = new FastApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FastApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FastApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FastApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The PlaylistCreate model constructor.
     * @property {module:model/PlaylistCreate}
     */
    PlaylistCreate,

    /**
     * The PlaylistUpdate model constructor.
     * @property {module:model/PlaylistUpdate}
     */
    PlaylistUpdate,

    /**
     * The RatingSchema model constructor.
     * @property {module:model/RatingSchema}
     */
    RatingSchema,

    /**
     * The URLCreateUpdate model constructor.
     * @property {module:model/URLCreateUpdate}
     */
    URLCreateUpdate,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
     * The ValidationErrorLocInner model constructor.
     * @property {module:model/ValidationErrorLocInner}
     */
    ValidationErrorLocInner,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The PlaylistApi service constructor.
    * @property {module:api/PlaylistApi}
    */
    PlaylistApi,

    /**
    * The SpotifyApi service constructor.
    * @property {module:api/SpotifyApi}
    */
    SpotifyApi,

    /**
    * The UrlApi service constructor.
    * @property {module:api/UrlApi}
    */
    UrlApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
