/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.PlaylistApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlaylistApi', function() {
    describe('deletePlaylistApiV1AdminPlaylistPlaylistIdDelete', function() {
      it('should call deletePlaylistApiV1AdminPlaylistPlaylistIdDelete successfully', function(done) {
        //uncomment below and update the code to test deletePlaylistApiV1AdminPlaylistPlaylistIdDelete
        //instance.deletePlaylistApiV1AdminPlaylistPlaylistIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlaylistApiV1AdminPlaylistPlaylistIdGet', function() {
      it('should call getPlaylistApiV1AdminPlaylistPlaylistIdGet successfully', function(done) {
        //uncomment below and update the code to test getPlaylistApiV1AdminPlaylistPlaylistIdGet
        //instance.getPlaylistApiV1AdminPlaylistPlaylistIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlaylistsApiV1AdminPlaylistGet', function() {
      it('should call getPlaylistsApiV1AdminPlaylistGet successfully', function(done) {
        //uncomment below and update the code to test getPlaylistsApiV1AdminPlaylistGet
        //instance.getPlaylistsApiV1AdminPlaylistGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('newPlaylistApiV1AdminPlaylistPost', function() {
      it('should call newPlaylistApiV1AdminPlaylistPost successfully', function(done) {
        //uncomment below and update the code to test newPlaylistApiV1AdminPlaylistPost
        //instance.newPlaylistApiV1AdminPlaylistPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut', function() {
      it('should call updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut successfully', function(done) {
        //uncomment below and update the code to test updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut
        //instance.updateCoverImageApiV1AdminPlaylistPlaylistIdCoverImagePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePlaylistApiV1AdminPlaylistPlaylistIdPut', function() {
      it('should call updatePlaylistApiV1AdminPlaylistPlaylistIdPut successfully', function(done) {
        //uncomment below and update the code to test updatePlaylistApiV1AdminPlaylistPlaylistIdPut
        //instance.updatePlaylistApiV1AdminPlaylistPlaylistIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
