/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.UrlApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UrlApi', function() {
    describe('activateOrDeactivateUrlApiV1AdminUrlUrlIdActivatePut', function() {
      it('should call activateOrDeactivateUrlApiV1AdminUrlUrlIdActivatePut successfully', function(done) {
        //uncomment below and update the code to test activateOrDeactivateUrlApiV1AdminUrlUrlIdActivatePut
        //instance.activateOrDeactivateUrlApiV1AdminUrlUrlIdActivatePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUrlApiV1AdminUrlUrlIdDelete', function() {
      it('should call deleteUrlApiV1AdminUrlUrlIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteUrlApiV1AdminUrlUrlIdDelete
        //instance.deleteUrlApiV1AdminUrlUrlIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUrlApiV1AdminUrlUrlIdGet', function() {
      it('should call getUrlApiV1AdminUrlUrlIdGet successfully', function(done) {
        //uncomment below and update the code to test getUrlApiV1AdminUrlUrlIdGet
        //instance.getUrlApiV1AdminUrlUrlIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUrlsApiV1AdminUrlGet', function() {
      it('should call getUrlsApiV1AdminUrlGet successfully', function(done) {
        //uncomment below and update the code to test getUrlsApiV1AdminUrlGet
        //instance.getUrlsApiV1AdminUrlGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('newUrlApiV1AdminUrlPost', function() {
      it('should call newUrlApiV1AdminUrlPost successfully', function(done) {
        //uncomment below and update the code to test newUrlApiV1AdminUrlPost
        //instance.newUrlApiV1AdminUrlPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUrlApiV1AdminUrlUrlIdPut', function() {
      it('should call updateUrlApiV1AdminUrlUrlIdPut successfully', function(done) {
        //uncomment below and update the code to test updateUrlApiV1AdminUrlUrlIdPut
        //instance.updateUrlApiV1AdminUrlUrlIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
